### ISSUE TITLE
Tracking issue: implicit and explicit snapshots

### ISSUE THREAD

**Issue by vweevers** [Level/community#118]
**Implicit snapshots**

Main task here is to fix the issue described in https://github.com/Level/leveldown/issues/796.

- [ ] `abstract-level` (semver-major, or opt-in): add tests that snapshot is created synchronously
- [ ] `classic-level` (semver-patch?): create snapshot synchronously

**Explicit snapshots**

This is a new feature. Prior discussions: https://github.com/Level/community/issues/45, https://github.com/Level/community/issues/47, https://github.com/Level/leveldown/issues/486.

- [ ] `abstract-level` (semver-minor): https://github.com/Level/abstract-level/pull/42
- [ ] `level-supports` (semver-minor): add `explicitSnapshots` property
- [ ] `abstract-level` (semver-minor): implement explicit snapshots
- [ ] `memory-level` (semver-minor): implement explicit snapshots (can just take a reference to the RB tree)
- [ ] `classic-level` (semver-minor): implement explicit snapshots
- [ ] `browser-level` (semver-patch): document that explicit snapshots are not available
- [ ] `level` (semver-patch): document explicit snapshots
- [ ] `many-level` (semver-minor): implement explicit snapshots
- [ ] `rave-level` (semver-minor): implement explicit snapshots
