### ISSUE TITLE
Epic: add `has()` and `hasMany()`

### ISSUE THREAD

**Issue by vweevers** [Level/community#142]
Per the feature request of https://github.com/Level/community/issues/106. Will add two methods:

```js
await db.put('love', 'u')
await db.has('love') // true
await db.hasMany(['love', 'hate']) // [true, false]
```

Tasks:

- [ ] `level-supports` (semver-minor): add `has` property
- [ ] `abstract-level` (semver-minor): implement `has()` and `hasMany()`
- [ ] `memory-level` (semver-minor): implement `has()` and `hasMany()`
- [ ] `classic-level` (semver-minor): implement `has()` and `hasMany()`
- [ ] `browser-level` (semver-minor): implement `has()` and `hasMany()`
- [ ] `many-level` (semver-minor): implement `has()` and `hasMany()`
- [ ] `rave-level` (semver-minor): implement `has()` and `hasMany()`
